### ISSUE TITLE
FYI - You can use exec

### ISSUE THREAD

**Issue by prelegalwonder** [gfacciol/zotero_dataserver-docker#1]
You probably already know this but you don't have to execute bash as the last step in the CMD sequence. 

You can run with -d instead of -ti and then anytime you need to connect to add a user or run an admin command you can just do:

`docker exec -ti FOO bash`

This is awesome btw. Thank you VERY VERY much for putting this together. I was working on this as well but kept getting snagged on little php zend things.

**Comment by gfacciol** [comment]
Thanks for the tip! I actually didn't know, but it makes sense. I'll update the Dockerfile and readme. 
By the way, I've also tried to setup a local Zotero Web-Library connected to the dataserver, without luck (you've probably seen the traces in the Dockerfile). Do you have any experience with that?

**Comment by prelegalwonder** [comment]
Oh cool, I haven't seen the web-library project at all. I'd be happy to try and give it a shot "dockerizing" it. I'll mess around with my fork and if I get something working I'll submit a pull request! :)
