### ISSUE TITLE
Installing on Raspberry Pi

### ISSUE THREAD

**Issue by bluebird11** [gfacciol/zotero_dataserver-docker#2]
I'm getting the following error when trying to install on a Raspberry Pi:

`standard_init_linux.go:178: exec user process caused "exec format error"`

Can you help?

**Comment by gfacciol** [comment]
Hi, I think the problem is that the image used in the Dockerfile is a 64bit debian

     FROM debian:wheezy-backports 

You should try changing the image to an ARM one as: armhfbuild/debian
(https://github.com/armhf-docker-library/debian)
