### ISSUE TITLE
Unexpected status code 403 caching ZFS credentials

### ISSUE THREAD

**Issue by nukedone** [gfacciol/zotero_dataserver-docker#3]
Everything went smooth until client sync error

Unexpected status code 403 caching ZFS credentials

using Zotero 4

**Comment by gfacciol** [comment]
did you Patch the standalone client to use the new dataserver as explained in the readme?

**Comment by nukedone** [comment]
It seems that the problem was an old database (from Zotero main servers). After patching I needed to start from scratch, export the old database and import it into the new instance. I successfully managed to set up the Zotero dataserver with this docker. Thanks a lot! The issue is solved.

**Comment by gfacciol** [comment]
:)
