### ISSUE TITLE
Can not add user

### ISSUE THREAD

**Issue by josschm** [gfacciol/zotero_dataserver-docker#5]
Hi,
I tried to run the docker build, but the add_user failed.
First of all I had to change the pactches/add_user script from:
`#!/usr/bin/php`
`<?`
`set_include_path("../include");`
to
`#!/usr/bin/php`
`<?php`
`set_include_path("../include");`

Then during build a get the following error:
`PHP Fatal error:  Class 'Z_CONFIG' not found in /srv/zotero/dataserver/admin/add_user on line 13
The command '/bin/sh -c service mysql start && service memcached start &&     cd /srv/zotero/dataserver/admin &&     ./add_user 101 test test &&     ./add_user 102 test2 test2 &&     ./add_group -o test -f members -r members -e members testgroup &&     ./add_groupuser testgroup test2 member' returned a non-zero code: 255`

Any Idea? Is there a other method for adding a user?

**Comment by kerstenj** [comment]
Hey,
I have the same issues. Adding 'php' seems to work but why is it not appearing in any of the other provided scripts? Are we missing something?
Thanks for any suggestions in advance.

**Comment by kerstenj** [comment]
Well, found the solution:
Open php.ini, find open_short_tag and set it to "On"

**Comment by kerstenj** [comment]
After setting the open_short_tag = On and installing memcache with
`apt-get install php5-memcache`
I was able to add the users and usergroup according to the Dockerfile.
Creating and adding the cert_override.txt solved SSL issues with the client (as described in your readme).
Tried to sync a test library with user test: The green arrow keeps rotating but nothing happens.
Response from
`curl -k -v -X POST -d "version=9&username=test&password=test" https://127.0.0.1:443/login`

```
Hostname was NOT found in DNS cache
Trying 127.0.0.1...
Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
successfully set certificate verify locations:
CAfile: none
CApath: /etc/ssl/certs
SSLv3, TLS handshake, Client hello (1):
SSLv3, TLS handshake, Server hello (2):
SSLv3, TLS handshake, CERT (11):
SSLv3, TLS handshake, Server key exchange (12):
SSLv3, TLS handshake, Server finished (14):
SSLv3, TLS handshake, Client key exchange (16):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
Server certificate:
 	 subject: [NONE]
 	 start date: 2016-08-18 15:56:16 GMT
 	 expire date: 2044-01-04 15:56:18 GMT
POST /login HTTP/1.1
User-Agent: curl/7.38.0
Host: 127.0.0.1
Accept: */*
Content-Length: 37
Content-Type: application/x-www-form-urlencoded
 
upload completely sent off: 37 out of 37 bytes
HTTP 1.0, assume close after body
HTTP/1.0 500 Internal Server Error
Date: Thu, 16 Aug 2018 09:39:24 GMT
Server: Apache/2.4.10 (Debian)
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8

Closing connection 0
SSLv3, TLS alert, Client hello (1):
```

**Comment by gfacciol** [comment]
Dear @josschm @kerstenj, 
The version running on debian jessie wasn't working as expected and I could't fix it. 
So I rolled back the image to use wheezy-backports.
